package view;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */


import controller.MultaDAO;
import model.Multa;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.logging.Logger;

/**
 *
 * @author jose
 */
public class frmMultas extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(frmMultas.class.getName());
    private final MultaDAO multaDAO;

    /**
     * Creates new form frmMultas
     */
    public frmMultas() {
        initComponents();
        this.setTitle("Gestion de multas");
        this.setLocationRelativeTo(null);
        multaDAO = new MultaDAO();
        configureTable();
    }

    private void configureTable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID Multa", "ID Prestamo", "Monto", "Fecha Emision", "Estado"}
        );
        tbtMultas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtMultas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnGenerarMulta = new javax.swing.JButton();
        btnRegistrarPago = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnCargarTodasMultas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdPrestamo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdMulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbtMultas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"ID Multa", "ID Prestamo", "Monto", "Fecha Emision", "Estado"}
        ));
        jScrollPane1.setViewportView(tbtMultas);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18));
        jLabel1.setText("Apartado de multas");

        btnGenerarMulta.setText("Generar Multa");
        btnGenerarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMultaActionPerformed(evt);
            }
        });

        btnRegistrarPago.setText("Registrar Pago");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnCargarTodasMultas.setText("Cargar Todas Multas");
        btnCargarTodasMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTodasMultasActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Usuario:");
        txtIdUsuario.setText("");

        jLabel3.setText("ID Prestamo:");
        txtIdPrestamo.setText("");

        jLabel4.setText("ID Multa:");
        txtIdMulta.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(64, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtIdMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnGenerarMulta)
                                                .addGap(30, 30, 30)
                                                .addComponent(btnRegistrarPago)
                                                .addGap(30, 30, 30)
                                                .addComponent(btnConsultar)
                                                .addGap(30, 30, 30)
                                                .addComponent(btnCargarTodasMultas)))
                                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtIdMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnGenerarMulta)
                                        .addComponent(btnRegistrarPago)
                                        .addComponent(btnConsultar)
                                        .addComponent(btnCargarTodasMultas))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnGenerarMultaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int idPrestamo = Integer.parseInt(txtIdPrestamo.getText().trim());
            double monto = multaDAO.calcularMultaPorRetraso(idPrestamo);
            if (monto > 0) {
                boolean success = multaDAO.generarMulta(idPrestamo, monto);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Multa generada exitosamente por $" + monto);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al generar la multa", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El préstamo no está retrasado o no existe", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de préstamo válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int idMulta = Integer.parseInt(txtIdMulta.getText().trim());
            boolean success = multaDAO.registrarPago(idMulta);
            if (success) {
                JOptionPane.showMessageDialog(this, "Pago registrado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el pago", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de multa válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int idUsuario = Integer.parseInt(txtIdUsuario.getText().trim());
            List<Multa> multas = multaDAO.consultarMultasPendientes(idUsuario);
            DefaultTableModel model = (DefaultTableModel) tbtMultas.getModel();
            model.setRowCount(0); // Clear table
            for (Multa multa : multas) {
                model.addRow(new Object[]{
                        multa.getIdMulta(),
                        multa.getIdPrestamo(),
                        multa.getMonto(),
                        multa.getFechaEmision(),
                        multa.getEstado()
                });
            }
            if (multas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay multas pendientes para este usuario", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de usuario válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCargarTodasMultasActionPerformed(java.awt.event.ActionEvent evt) {
        List<Multa> multas = multaDAO.consultarTodasMultas();
        DefaultTableModel model = (DefaultTableModel) tbtMultas.getModel();
        model.setRowCount(0); // Clear table
        for (Multa multa : multas) {
            model.addRow(new Object[]{
                    multa.getIdMulta(),
                    multa.getIdPrestamo(),
                    multa.getMonto(),
                    multa.getFechaEmision(),
                    multa.getEstado()
            });
        }
        if (multas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay multas registradas en el sistema", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMultas().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGenerarMulta;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JButton btnCargarTodasMultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtMultas;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtIdPrestamo;
    private javax.swing.JTextField txtIdMulta;
    // End of variables declaration
}